# -*- coding: utf-8 -*-
"""Car detection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11RMvMejR-cCDb7YfxH3YAmGc50a6tlb2

Import libraries
"""

from google.colab.patches import cv2_imshow
 import cv2

cap = cv2.VideoCapture( 'cars.mp4')

car_cascade = cv2.CascadeClassifier('cars.xml')

while True:
    # reads frames from a video
    ret, frames = cap.read()
    # convert to gray scale of each frames
    gray = cv2.cvtColor(frames, cv2.COLOR_BGR2GRAY)
    
    # Detects cars of different sizes in the input image
    cars = car_cascade.detectMultiScale( gray, 1.1, 1)
    # To draw a rectangle in each cars
    for (x,y,w,h) in cars:
        cv2.rectangle(frames,(x,y),(x+w,y+h),(0,0,255),2)
        # Display frames in a window
        cv2_imshow(frames)
    # Wait for Enter key to stop
    if cv2.waitKey(33) == 27:
        break


cv2.destroyAllWindows()